### ISSUE TITLE
Question about setting is_training in normalizer params

### ISSUE THREAD

**Issue by VashishtMadhavan** [google-research/morph-net#33]
Generally, we use a placeholder for the `is_training` flag of `normalizer_params` for batch norm to toggle between training and test mode. When using morph net regularization though, we can't set `is_training` to a placeholder since we see the following error:
```
Traceback (most recent call last):
  File "gamma_prune.py", line 47, in <module>
    network_regularizer = latency_regularizer.GammaLatencyRegularizer([out.op], gamma_threshold=gamma_scale, hardware='K80')
  File "/Users/vashishtmadhavan/Documents/Code/morph-net/morph_net/network_regularizers/latency_regularizer.py", line 90, in __init__
    force_group=force_group, regularizer_blacklist=regularizer_blacklist)
  File "/Users/vashishtmadhavan/Documents/Code/morph-net/morph_net/framework/op_regularizer_manager.py", line 126, in __init__
    self._op_handler_dict[op.type].assign_grouping(op, self)
  File "/Users/vashishtmadhavan/Documents/Code/morph-net/morph_net/framework/grouping_op_handler.py", line 35, in assign_grouping
    input_ops, op_reg_manager)
  File "/Users/vashishtmadhavan/Documents/Code/morph-net/morph_net/framework/op_handler_util.py", line 73, in get_ops_without_groups
    op_slices = op_reg_manager.get_op_slices(op)
  File "/Users/vashishtmadhavan/Documents/Code/morph-net/morph_net/framework/op_regularizer_manager.py", line 437, in get_op_slices
    size = op_handler_util.get_op_size(op)
  File "/Users/vashishtmadhavan/Documents/Code/morph-net/morph_net/framework/op_handler_util.py", line 505, in get_op_size
    shape = op.outputs[0].shape.as_list()
  File "/Users/vashishtmadhavan/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/tensor_shape.py", line 904, in as_list
    raise ValueError("as_list() is not defined on an unknown TensorShape.")
ValueError: as_list() is not defined on an unknown TensorShape.
``` 
What's the appropriate strategy here? Would we just set `is_training` to False for both training and testing or True?

**Comment by eladeban** [comment]
The short answer is to use  `is_training=True`.

This must be so as you want batch norm params to be updated and network use batch statistic during training. However not freezing stats during test will result in a more noisy test accuracy (possibly lower), this is not really a problem as you don't care too much about the accuracy during the structure learning phase where the MorphNet regularizer is on. During the retraining phase, you of course do not need the network regularizer at all and you will be able to pass `is_training` as a place holder with no problem. 

BTW, is there a specific reason you are using `is_training` as a place holder?

**Comment by VashishtMadhavan** [comment]
I see that makes sense. I found a work around where I'm just separating the training and validation so i removed the need for a placeholder. thanks for the help
