### ISSUE TITLE
Doesn't work with Deconvolutions

### ISSUE THREAD

**Issue by VashishtMadhavan** [google-research/morph-net#57]
Hi, Im currently trying to train a simple ConvAE on MNIST, using a `GammaFlopsRegularizer` on `out.op` of the following network
```
def conv_ae(x_ph, is_training, scope, channels=[32, 64, 64], reuse=False):
    norm_params = {'is_training': is_training, 'scale': True, 'center': False}
    # Network Definition
    with tf.variable_scope(scope, reuse=reuse):
        with slim.arg_scope([slim.conv2d, slim.fully_connected],
                      normalizer_fn=slim.batch_norm,
                      normalizer_params=norm_params,
                      weights_initializer=tf.truncated_normal_initializer(0.0, 0.01),
                      weights_regularizer=slim.l2_regularizer(0.0005)):
            conv1 = slim.conv2d(x_ph, num_outputs=channels[0], kernel_size=3, scope='conv1')
            pool1 = slim.max_pool2d(conv1, kernel_size=2, scope='pool1')
            conv2 = slim.conv2d(pool1, num_outputs=channels[1], kernel_size=3, scope='conv2')
            pool2 = slim.max_pool2d(conv2, kernel_size=2, scope='pool2')
            conv3 = slim.conv2d(pool2, num_outputs=channels[2], kernel_size=3, scope='conv3')

            # deconv part
            deconv1 = slim.conv2d_transpose(conv3, num_outputs=channels[2], kernel_size=3, stride=2, scope='conv_transpose1')
            deconv2 = slim.conv2d_transpose(deconv1, num_outputs=channels[1], kernel_size=3, stride=2, scope='conv_transpose2')
            out = slim.conv2d_transpose(deconv2, num_outputs=1, kernel_size=3, stride=1, activation_fn=tf.nn.sigmoid, scope='conv_output')
    return out
```
However, I'm seeing the `OpRegularizerManager` hit the iteration limit and found the following error:

```
Traceback (most recent call last):
  File "deconv_test.py", line 33, in <module>
    network_regularizer = flop_regularizer.GammaFlopsRegularizer([pred.op], gamma_threshold=gamma_scale)
  File "/Users/vashishtmadhavan/Documents/Code/morph-net/morph_net/network_regularizers/flop_regularizer.py", line 66, in __init__
    regularizer_blacklist=regularizer_blacklist)
  File "/Users/vashishtmadhavan/Documents/Code/morph-net/morph_net/framework/op_regularizer_manager.py", line 132, in __init__
    ['%s (%s)' % (o.name, o.type) for o in self._op_deque])
RuntimeError: OpRegularizerManager could not handle ops: ['base/conv_transpose1/conv2d_transpose (Conv2DBackpropInput)', 'base/conv_output/Sigmoid (Sigmoid)', 'base/conv_output/BiasAdd (BiasAdd)', 'base/conv_output/conv2d_transpose (Conv2DBackpropInput)', 'base/conv_transpose2/Relu (Relu)', 'base/conv_transpose2/BiasAdd (BiasAdd)', 'base/conv_transpose2/conv2d_transpose (Conv2DBackpropInput)', 'base/conv_transpose1/Relu (Relu)', 'base/conv_transpose1/BiasAdd (BiasAdd)', 'base/conv_transpose1/stack (Pack)']
```
Any thoughts on handling deconvs?

**Comment by eladeban** [comment]
Hi thanks for pointing this out,
Two things are missing, one is a line in op_handlers.py (see  #58 )
The other is batch norm after conv2d_transpose, could you try it out?

**Comment by VashishtMadhavan** [comment]
cool, looks like that worked
